name: Deploy Node.js App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: testingca
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Node.js Application
        run: npm run build
          
      - name: Archive Files for Deployment
        run: zip -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} . -x '*.git*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
