name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log: Setting up Terraform
        run: echo "Setting up Terraform..."

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Log: Installing Ansible
        run: echo "Installing Ansible..."

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Log: Running Terraform to provision resources
        run: echo "Running Terraform..."

      - name: Run Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Log: Running Ansible playbook for application deployment
        run: echo "Running Ansible Playbook..."

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          cd ansible
          ansible-playbook -i ../terraform/dynamic_inventory.ini deploy_nodejs_app.yml
