name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.5

    # Step 3: Terraform Initialize
    - name: Initialize Terraform
      run: terraform init

    # Step 4: Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Step 5: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Step 6: Set up Ansible
    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    # Step 7: Run Ansible Playbook
    - name: Run Ansible Playbook
      run: ansible-playbook -i dynamic_inventory.ini ansible/deploy_nodejs_app.yml
